export type Gender = "male" | "female" | "other";

/** Drives date rules on the hero form and pricing (room nights vs single-day venue). */
export type BookingKind = "room" | "venue" | "both";

/** Venue event tier; each venue has separate amounts for wedding, birthday, and Meeting/Seminar. */
export type VenueEventType = "wedding" | "birthday" | "meeting_staff";

/** Room inventory `type` values (matches backend `rooms.type` enum). */
export type RoomTypeFilter = "standard" | "family" | "deluxe";

export type BedSpecificationValue =
  | string
  | {
      specification?: string;
      label?: string;
      name?: string;
      type?: string;
      bed_type?: string;
      value?: string;
      quantity?: number | string;
      [key: string]: unknown;
    };

export interface BookingResponse {
  message: string;
  guest?: unknown;
  booking?: {
    reference_number: string;
    receipt_token?: string;
    [key: string]: unknown;
  };
  /** @deprecated use booking instead */
  bookings?: Array<{ reference_number: string; [key: string]: unknown }>;
  total_price?: number;
  /** Xendit payment page URL (present when payment_method is 'online') */
  payment_url?: string | null;
  /** True until the guest opens the signed link from their email */
  email_verification_required?: boolean;
}

/** API 422 response when date range conflicts with existing booking */
export interface BookingConflictResponse {
  message: string;
  error?: "date_range_conflict";
  conflicts?: {
    rooms?: Array<{ id: number; name: string }>;
    venues?: Array<{ id: number; name: string }>;
    room_lines?: Array<{
      room_type: string;
      inventory_group_key: string;
      requested: number;
      available: number;
    }>;
  };
}

/** API response shape for GET /bookings/receipt/:token or GET /bookings/reference/:reference */
export interface BookingReferenceResponse {
	/** ISO 8601 — settle by 9:00 PM Asia/Manila on the check-in calendar day (matches Booking::unpaidExpiresAt). */
	unpaid_expires_at?: string | null;
	unpaid_expiry_days?: number;
	/** True when check-in is far enough ahead to show the 3-day / down-payment policy on the receipt. */
	down_payment_notice_applies?: boolean;
	down_payment_notice_min_lead_days?: number;
	/** Deposit share of total from admin payment settings (partial_payment_options[0]). */
	down_payment_percent?: number;
	/**
	 * When booking is cancelled with refund pending/refunded and guest had paid:
	 * policy breakdown for billing statement transparency.
	 */
	cancellation_refund?: {
		fee_percent: number;
		fee_from_total: number;
		amount_paid: number;
		retained: number;
		refund_to_guest: number;
		/** When true, admin cancellation % applies; when false, partial payment is non-refundable reservation fee. */
		applies_cancellation_percent?: boolean;
		settlement_type?: "full_settlement" | "partial_deposit";
		statement_note?: string;
	};
	/** True when check-in is strictly after today (Manila): Messenger settlement instructions. */
	use_messenger_deposit_instructions?: boolean;
	payment?: {
		method?: string;
		plan?: string;
		invoice_id?: string;
		invoice_url?: string;
		can_retry?: boolean;
		amount_paid?: number;
		balance?: number;
		amount_due_now?: number;
	};
	/** Signed PDF download URL generated by the backend with Laravel's URL::temporarySignedRoute(). */
	billing_statement_pdf_url?: string;
	booking?: {
		reference_number: string;
		/** Opaque public id for receipt URL (UUID). */
		receipt_token?: string;
		booking_status?: string;
		payment_status?: string;
		/** @deprecated merged into booking_status + payment_status */
		status?: string;
		check_in?: string;
		check_out?: string;
		no_of_days?: number;
		venue_event_type?: string | null;
		total_price?: string | number;
		special_discount_type?: string | null;
		special_discount_value?: string | number | null;
		special_discount_original_total_price?: string | number | null;
		special_discount_amount_applied?: string | number | null;
		payment_method?: string;
		online_payment_plan?: string;
		xendit_invoice_id?: string;
		xendit_invoice_url?: string;
		created_at?: string;
		guest?: {
			first_name?: string;
			middle_name?: string | null;
			last_name?: string;
			email?: string;
			contact_num?: string;
			street?: string;
			barangay?: string;
			municipality?: string;
			province?: string;
			region?: string;
			[key: string]: unknown;
		};
		rooms?: Array<{
			name?: string;
			type?: string;
			capacity?: number;
			price?: string | number;
			bed_specifications?: BedSpecificationValue[];
			[key: string]: unknown;
		}>;
		venues?: Array<{
			name?: string;
			capacity?: number;
			price?: string | number;
			[key: string]: unknown;
		}>;
		[key: string]: unknown;
	};
	qr_code_url?: string | null;
	/** True when a testimonial/site review has already been submitted for this booking. */
	has_testimonial?: boolean;
	/** From API when booking is not yet email-confirmed */
	email_verification_required?: boolean;
}

/** Receipt view model for Step5 (from booking API payload). */
export interface BookingReceipt {
	/** QR code image URL for check-in */
	qr_code_url?: string | null;
	reference_number: string;
	created_at: string;
	booking_status: string;
	payment_status: string;
	check_in: string;
	check_out: string;
	issued_on: string;
	nights: number;
	guest_name: string;
	guest_email: string;
	guest_contact: string;
	guest_address: string;
	/** Assigned physical rooms (optional until staff assigns). */
	rooms?: Array<{
			name: string;
			type: string;
			capacity: number;
			price: number | string;
			/** Some API payloads use `number` for assigned room # */
			number?: number | null;
			bed_specifications?: BedSpecificationValue[];
		}>;
	/** Requested room types from guest checkout (no room name yet). */
	room_lines?: Array<{
		room_type: string;
		inventory_group_key: string;
		quantity: number;
		unit_price_per_night: number | string;
	}>;
	/** True when stay includes accommodation (show check-in/out times on receipt). */
	has_room_stay?: boolean;
	email_verification_required?: boolean;
	/** Multiple venues */
	venues?: Array<{
		name: string;
		capacity: number;
		price?: number | string;
		wedding_price?: number | string;
		birthday_price?: number | string;
		meeting_staff_price?: number | string;
	}>;
	/** Stored when the booking includes venues */
	venue_event_type?: string | null;
	/** @deprecated use rooms instead */
	room?: {
		number: number | null;
		type: string;
		capacity: number;
		price: string;
		bed_specifications?: BedSpecificationValue[];
	};
	subtotal: string;
	grand_total: string;
	special_discount_type?: string | null;
	special_discount_value?: number;
	special_discount_original_total_price?: number;
	special_discount_amount_applied?: number;
	/** ISO 8601 — settle by 9:00 PM Asia/Manila on the check-in calendar day. */
	unpaid_expires_at?: string | null;
	unpaid_expiry_days?: number;
	down_payment_notice_applies?: boolean;
	down_payment_notice_min_lead_days?: number;
	/** Deposit share of total from admin payment settings. */
	down_payment_percent?: number;
	use_messenger_deposit_instructions?: boolean;
	payment_method?: string;
	online_payment_plan?: string;
	invoice_id?: string;
	invoice_url?: string;
	can_retry_payment?: boolean;
	amount_paid?: number;
	balance?: number;
	amount_due_now?: number;
	/** Set from API when cancelled + refund pipeline + guest had paid. */
	cancellation_refund?: {
		fee_percent: number;
		fee_from_total: number;
		amount_paid: number;
		retained: number;
		refund_to_guest: number;
		applies_cancellation_percent?: boolean;
		settlement_type?: "full_settlement" | "partial_deposit";
		statement_note?: string;
	};
	/** Signed PDF download URL generated by the backend with Laravel's URL::temporarySignedRoute(). */
	billing_statement_pdf_url?: string;
}

/** Room row from the multi-step cart (Step 1) — physical assignment comes later. */
export interface FormDataRoom {
  name?: string;
  type?: string;
  description?: string | null;
  bed_specifications?: BedSpecificationValue[] | null;
  capacity?: number;
  price?: number | string;
  room_number?: number | null;
  number?: number | null;
  /** Present on some receipt-derived rows (Step 5 display). */
  status?: string;
}

/** Venue row from the multi-step cart. */
export interface FormDataVenue {
  /** Cart / API venue id for POST /bookings (see `toId` in booking.utils). */
  id?: number;
  name: string;
  capacity?: number;
  price?: number | string;
  wedding_price?: number | string;
  birthday_price?: number | string;
  meeting_staff_price?: number | string;
}

/** Room-type line (no room name until staff assigns) — used on Step 5 from API. */
export interface Step5RoomLineRow {
  kind: "line";
  room_type: string;
  inventory_group_key: string;
  quantity: number;
  price: number;
}

/** Union of cart rooms and line-only rows shown on the receipt. */
export type Step5DisplayRoom = FormDataRoom | Step5RoomLineRow;

export interface FormData {
  reference_number?: string;
  current_step: number;
  /** What the guest is booking: stay only, event space only, or both */
  booking_type: BookingKind;
  /** For `both`: calendar day of the venue/event (same-day use). Used for venue availability API. */
  venue_event_date: string;
  /** Required when `venues` is non-empty; drives venue line pricing. */
  venue_event_type: VenueEventType | "";
  check_in: string;
  check_out: string;
  days: number;
  /**
   * For `room` and `both`: which room types to show on step 1 (one or more).
   * Ignored for `venue`-only bookings.
   */
  room_type_filters: RoomTypeFilter[];
  rooms: FormDataRoom[];
  venues: FormDataVenue[];

  firstName: string;
  middleName: string | null;
  lastName: string;
  gender: Gender | "";
  phone: string;
  email: string;
  address: string;

  region: string;
  street: string;
  city: string;
  state: string;
  zipCode: string;

  category: string;
  newsletter: boolean;
  notifications: boolean;
  paymentMethod: string;
  onlinePaymentPlan: "" | "full" | `partial_${number}`;

  totalPrice: number;
  grandTotalPrice: number;
  /** Set when booking is created from API response (optional). */
  booking_status?: string;
  payment_status?: string;
}

export interface PersonalDetails {
  firstName: string;
  middleName: string | null;
  lastName: string;
  gender: Gender;
  phone: string;
  email: string;
  address: string;
}

/** Collapsed room-type lines for POST /bookings (no specific room id). */
export interface RoomLinePayload {
  room_type: string;
  inventory_group_key: string;
  quantity: number;
  unit_price: number;
}

export interface BookingPayload {
  reference_number?: string;
  payment_method?: string;
  online_payment_plan?: "full" | `partial_${number}`;
  check_in: string;
  check_out: string;
  days: number;
  /** Guest booking: room type + bed-spec lines (staff assigns physical rooms later). */
  room_lines?: RoomLinePayload[];
  venues?: number[];
  venue_event_type?: string;
  total_price: number;
  grand_total_price?: number;
  first_name: string;
  middle_name: string | null;
  last_name: string;
  email: string;
  contact_num: string;
  gender: Gender;
  is_international: boolean;
  country?: string | null;
  region?: string | null;
  province: string | null;
  municipality: string | null;
  barangay: string | null;
  street: string;
  address: string;
  zip_code: string;
  category: string;
  newsletter: boolean;
  notifications: boolean;
  city: string | null;
  captcha_token?: string;
  /** Honeypot — must stay empty */
  website?: string;
}
